### ISSUE TITLE
(typo) allDocs.DocContainer signature is misleading

### ISSUE THREAD

**Issue by fredgalvao** [AGBrown/pouchdb.d.ts#15]
TLDR:

> D extends ExistingDoc, DocContainer does not.

According to the current signature of DocContainer:

``` typescript
interface DocContainer<D> extends ExistingDoc {
    /** The document */
    doc: D;
    /** The document id */
    id: string;
    /** The document key */
    key: string;
    /** @todo not sure what this is */
    value: {
        rev: string;
        deleted?: boolean;
    }
}
```

, a DocContainer would have both `[doc, id, key, value]` AND `[_id, _rev, _attachments]` inherited from ExistingDoc, which is not true. According to a test on pouchdb.com as of now, that object comes like this:

``` json
        {
            "id": "dave@gmail.com",
            "key": "dave@gmail.com",
            "value": {
                "rev": "1-f07c07ead1f2c9321c912fbb85aba100"
            },
            "doc": {
                "name": "David",
                "age": 68,
                "_id": "dave@gmail.com",
                "_rev": "1-f07c07ead1f2c9321c912fbb85aba100"
            }
        }
```

which proves my point that

``` typescript
interface DocContainer<D> extends ExistingDoc
```

should actually be

``` typescript
interface DocContainer<D extends ExistingDoc>
```

**Comment by AGBrown** [comment]
Also http://pouchdb.com/api.html#batch_fetch shows the following data structure returned from an `allDocs` call:

```
{
  "offset": 0,
  "total_rows": 1,
  "rows": [{
    "doc": {
      "_id": "0B3358C1-BA4B-4186-8795-9024203EB7DD",
      "_rev": "1-5782E71F1E4BF698FA3793D9D5A96393",
      "title": "Sound and Vision",
      "_attachments": {
        "attachment/its-id": {
          "content_type": "image/jpg",
          "data": "R0lGODlhAQABAIAAAP7//wAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==",
          "digest": "md5-57e396baedfe1a034590339082b9abce"
        }
      }
    },
   "id": "0B3358C1-BA4B-4186-8795-9024203EB7DD",
   "key": "0B3358C1-BA4B-4186-8795-9024203EB7DD",
   "value": {
    "rev": "1-5782E71F1E4BF698FA3793D9D5A96393"
   }
 }]
}
```

From what I can see [3d11f00](https://github.com/AGBrown/pouchdb.d.ts/commit/3d11f002c3511afbd5474a99b66bba56c1b5d22c#diff-20ca78683773edb5bfb1eafb0a825069R207) is where that interface was first added to the d.ts, and it's definition hasn't (really) changed since that commit. So the signature `interface DocContainer<D> extends ExistingDoc` is still as it was in that commit (i.e. I didn't change it deliberately later on). I think what I'm saying is it may well have been a typo in that original commit. 

I'll need to look at this again next week when I have more time to be sure. I would encourage a PR for this, @fredgalvao, if you have the time.

**Comment by nolanlawson** [comment]
Yes, this seems right. The response from allDocs/query will never have an _id/_rev/etc at the root level.

**Comment by AGBrown** [comment]
Thank you @fredgalvao for the fix, and @nolanlawson for the confirmation
